export const TOOGLE_FORM = 'TOGGLE_FORM';
export const OPEN_FORM = 'OPEN_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';
export const SHOW_ALL_TASKS = 'SHOW_ALL_TASKS';
export const SAVE_TASK = 'SAVE_TASK'; // Add task & Edit task
export const EDIT_TASK = 'EDIT_TASK'; // Update task
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK'; // Toggle status
export const FILTER_IN_TABLE = 'FILTER_IN_TABLE';
export const SEARCH_TASK = 'SEARCH_TASK';
export const SORT_TASK = 'SORT_TASK';